import { Contact, Group } from '@/types';

export const sampleContacts: Contact[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    fullName: 'John Doe',
    email: 'john.doe@kms-technology.com',
    phone: '+1 (555) 123-4567',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    location: 'Ho Chi Minh City',
    groups: ['1', '2'],
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    fullName: 'Jane Smith',
    email: 'jane.smith@kms-technology.com',
    phone: '+1 (555) 987-6543',
    department: 'Product Management',
    position: 'Product Manager',
    location: 'Atlanta',
    groups: ['2'],
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Johnson',
    fullName: 'Michael Johnson',
    email: 'michael.johnson@kms-technology.com',
    phone: '+1 (555) 456-7890',
    department: 'Engineering',
    position: 'Tech Lead',
    location: 'Ho Chi Minh City',
    groups: ['1'],
  },
  {
    id: '4',
    firstName: 'Sarah',
    lastName: 'Williams',
    fullName: 'Sarah Williams',
    email: 'sarah.williams@kms-technology.com',
    phone: '+1 (555) 321-6547',
    department: 'Design',
    position: 'UX Designer',
    location: 'Atlanta',
    groups: ['3'],
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Brown',
    fullName: 'David Brown',
    email: 'david.brown@kms-technology.com',
    phone: '+1 (555) 789-1234',
    department: 'QA',
    position: 'QA Engineer',
    location: 'Ho Chi Minh City',
    groups: ['1', '3'],
  },
];

export const sampleGroups: Group[] = [
  {
    id: '1',
    name: 'Engineering Team',
    description: 'All software engineers and tech leads',
    members: ['1', '3', '5'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Product Team',
    description: 'Product managers and related roles',
    members: ['1', '2'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    name: 'Design & QA',
    description: 'Design and quality assurance team',
    members: ['4', '5'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-25'),
  },
];

export const sampleUser = {
  id: 'demo-user',
  username: 'demo',
  email: 'demo@kms-technology.com',
  token: 'demo-token-12345',
  firstName: 'Demo',
  lastName: 'User',
};
